### PR TITLE
Add new Py Utils matplotlib

### PR DESCRIPTION
**Pull request by marcodieba**
Matplotlib is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms

### CODE REVIEW

**Comment by Lonami** [comment]
This isn't an utility… it's just an example of how to use a library. There are tons of examples on the official site even.

**Comment by marcodieba** [comment]
Sorry for not understanding, I understood that I wanted only indications of libs

**Comment by Lonami** [comment]
Sorry, the goal is to add more utilities (i.e. code snippets that can be helpful for other people), not only say, how to use a certain library.

**Comment by marcodieba** [comment]
okay i understand now

**Pull request closed without merging**
